### ISSUE TITLE
overwriting errors in InitUserDataLayer()

### ISSUE THREAD

**Issue by cryptix** [Isted/StreetCRUD#1]
Hi,

as far as I can tell the way you [prepare](https://github.com/Isted/StreetCRUD/blob/master/examples/UsesGeneratedCode/models/user.go#L228) the `sql.Stmt`s an error might be overwritten by a later, successful `db.Prepare()` call.

Since we are dealing with a list of strings and `*sql.Stmt`s here, how about something like this:

```go
func InitUserDataLayer(db *sql.DB) error {
	var err error
	if !userSQL.Init {

		stmts := []struct {
			sqlstr string
			stmt   *sql.Stmt
		}{
			{stmt: userSQL.GetByID, sqlstr: "SELECT login_id, name, email, password, deleted_user, del_on FROM vikiblog.public.user WHERE login_id = $1 and (deleted_user = $2 or deleted_user = $3)"},
			{stmt: userSQL.Update, sqlstr: "UPDATE vikiblog.public.user SET name = $1, email = $2, password = $3, deleted_user = $4, del_on = $5 WHERE login_id = $6"},
			{stmt: userSQL.Insert, sqlstr: "INSERT INTO vikiblog.public.user (name, email, password, deleted_user, del_on) VALUES ($1, $2, $3, $4, $5) RETURNING login_id"},
			{stmt: userSQL.MarkDel, sqlstr: "UPDATE vikiblog.public.user SET deleted_user = $1, del_on = $2 WHERE login_id = $3"},
			// etc...
		}

		for _, s := range stmts {
			s.stmt, err = db.Prepare(s.sqlstr)
			if err != nil {
				return err
			}
		}
		userSQL.Init = true
		userSQL.DB = db
	}
	return nil
}
```

If some kind of database up/downgrade causes my database layer to be half-initialized I want to least get the error from it.

**Comment by Isted** [comment]
Hi Henry,

Great catch, thank you. I think I assumed that if one failed they'd all fail because I assumed it would be an issue with *sql.DB, but, as we all know, assumptions can come back to bite you. I'll make the change. Thanks again for the contribution. If you ever want to make a PR in the future, just let me know.
